version: '3.8'

services:
  evolution-api:
    image: evolutionapi/evolution-api:v1.2.0  # Cambia a una versión específica
    container_name: evolution-api
    ports:
      - "3000:3000"
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - DATABASE_ENABLED=${DATABASE_ENABLED}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - CACHE_REDIS_ENABLED=${CACHE_REDIS_ENABLED}
    volumes:
      - evolution-data:/data

volumes:
  evolution-data:
